export const START_LOADING = 'START_LOADING'
export const END_LOADING = 'END_LOADING'

export const SET_ALERT = 'SET_ALERT'
export const REMOVE_ALERT = 'REMOVE_ALERT'
export const REMOVE_ALL_ALERTS = 'REMOVE_ALL_ALERTS'

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAIL = 'REGISTER_FAIL'

export const USER_LOADED = 'USER_LOADED'
export const AUTH_ERROR = 'AUTH_ERROR'

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'
export const LOGOUT = 'LOGOUT'

// export const ACCOUNT_DELETED = "ACCOUNT_DELETED"

export const GET_PAGE = 'GET_PAGE'
export const PAGE_ERROR = 'PAGE_ERROR'
export const SHOW_TASK = 'SHOW_TASK'
export const MOVE_TASK = 'MOVE_TASK'

export const CREATE_PROGRESS = 'CREATE_PROGRESS'
export const UPDATE_PROGRESS = 'UPDATE_PROGRESS'
export const DELETE_PROGRESS = 'DELETE_PROGRESS'

export const CREATE_GROUP = 'CREATE_GROUP'
export const UPDATE_GROUP = 'UPDATE_GROUP'
export const DELETE_GROUP = 'DELETE_GROUP'

export const CREATE_TASK = 'CREATE_TASK'
export const UPDATE_TASK = 'UPDATE_TASK'
export const DELETE_TASK = 'DELETE_TASK'

export const GOOGLE_CALENDAR_ADD_ACCOUNT = 'GOOGLE_CALENDAR_ADD_ACCOUNT'
export const GOOGLE_CALENDAR_LOADED = 'GOOGLE_CALENDAR_LOADED'
export const GOOGLE_CALENDAR_AUTH_ERROR = 'GOOGLE_CALENDAR_AUTH_ERROR'
export const GOOGLE_CALENDAR_CHANGE_CALENDAR_VISIBILITY =
   'GOOGLE_CALENDAR_CHANGE_CALENDAR_VISIBILITY'
export const GOOGLE_CALENDAR_UPDATE_EVENT = 'GOOGLE_CALENDAR_UPDATE_EVENT'
export const GOOGLE_CALENDAR_ADD_EVENT = 'GOOGLE_CALENDAR_ADD_EVENT'

export const FILTER_SCHEDULE = 'FILTER_SCHEDULE'
