export const START_LOADING = 'START_LOADING'
export const END_LOADING = 'END_LOADING'

export const SET_ALERT = 'SET_ALERT'
export const REMOVE_ALERT = 'REMOVE_ALERT'
export const REMOVE_ALL_ALERTS = 'REMOVE_ALL_ALERTS'

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAIL = 'REGISTER_FAIL'

export const USER_LOADED = 'USER_LOADED'
export const AUTH_ERROR = 'AUTH_ERROR'

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'
export const LOGOUT = 'LOGOUT'

// export const ACCOUNT_DELETED = "ACCOUNT_DELETED"

export const GET_PAGE = 'GET_PAGE'
export const PAGE_ERROR = 'PAGE_ERROR'
export const SHOW_TASK = 'SHOW_TASK'

export const GOOGLE_CALENDAR_LOADED = 'GOOGLE_CALENDAR_LOADED'
export const GOOGLE_CALENDAR_AUTH_ERROR = 'GOOGLE_CALENDAR_AUTH_ERROR'
export const GOOGLE_CALENDAR_SYNCED_EVENT_LOADING =
   'GOOGLE_CALENDAR_SYNCED_EVENT_LOADING'
export const GOOGLE_CALENDAR_CHANGE_CALENDAR_VISIBILITY =
   'GOOGLE_CALENDAR_CHANGE_CALENDAR_VISIBILITY'
export const CREATE_GOOGLE_EVENT = 'CREATE_GOOGLE_EVENT'
